name: Lint

on:
  push:
    branches: [ master, main, dev, update-node-version ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Run Lint
        working-directory: frontend
        run: npm run lint

  lint-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: admin
        run: npm ci
      - name: Run Lint
        working-directory: admin
        run: npm run lint
